### ISSUE TITLE
Bug: MAX_TEXTURES constant

### ISSUE THREAD

**Issue by vaga** [pixijs/pixijs#10545]
### Current Behavior

I have this error on my tests after upgrading to 8.1.4: 
```
TypeError: canvas.getContext is not a function
 ❯ getTestContext ../node_modules/pixi.js/src/rendering/renderers/gl/shader/program/getTestContext.ts:19:26
 ❯ maxRecommendedTextures ../node_modules/pixi.js/src/rendering/renderers/shared/texture/utils/maxRecommendedTextures.ts:12:16
 ❯ ../node_modules/pixi.js/src/rendering/batcher/shared/const.ts:3:29
```

### Expected Behavior

Don't get an error when running node test with an import of pixi.js

### Steps to Reproduce

Run a js file with node with an import of pixi.js

### Environment

- **`pixi.js` version**: *8.1.4*

### Possible Solution

`MAX_TEXTURES` is no more a constant. It depends of context.

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital I think we need to defer the call for maxtexutures until it is used. Also, that function should handle non-gl environments gracefully.

**Comment by GoodBoyDigital** [comment]
agree! was trying to avoid changing too much code...
