### ISSUE TITLE
Regression in event types 

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixijs#8783]
Issue caused by #7718 when attempting to build `@pixi/webworker` (no events).

```
node_modules/@pixi/display/lib/DisplayObject.d.ts:10:67 - error TS2694: Namespace 'GlobalMixins' has no exported member 'FederatedEventEmitterTypes'.

10 export declare type DisplayObjectEventEmitterTypes = GlobalMixins.FederatedEventEmitterTypes & {
```

Version: 7.0.0-beta.5
