### ISSUE TITLE
Bug: Tutorial code doesn't compile in TypeScript and PixiJS 7.3.2

### ISSUE THREAD

**Issue by martinsik** [pixijs/pixijs#9842]
### Current Behavior

I took the code example from the tutorial and I'm trying to compile it in TypeScript with the latest PIXI.JS and TypeScript versions. It throws errors:

```
[1] node_modules/@types/css-font-loading-module/index.d.ts(22,9): error TS2717: Subsequent property declarations must have the same type.  Property 'display' must be of type 'FontDisplay', but here has type 'string'.
[1] node_modules/@types/css-font-loading-module/index.d.ts(42,9): error TS2717: Subsequent property declarations must have the same type.  Property 'display' must be of type 'FontDisplay', but here has type 'string'.
```

https://github.com/martinsik/pixijs-7-typescript/blob/main/src/lib/index.ts

### Expected Behavior

It should compile without any errors.

### Steps to Reproduce

```
$ git clone https://github.com/martinsik/pixijs-7-typescript/
$ cd pixijs-7-typescript
$ npm ci
$ npm run serve
```

This will start concurrently a development server and TypeScript compiler in watch mode.

### Environment

- **`pixi.js` version**: *7.3.2*
- **OS & Version**: *OSX 13.6.1*
- **TypeScript version**: *5.2.2*

**Comment by martinsik** [comment]
Looks like hardcoding `@types/css-font-loading-module` version helped and i now compiles with the latest TypeScript and PixiJS versions:

```
"@types/css-font-loading-module": "0.0.10"
```

**Comment by bigtimebuddy** [comment]
Thanks for letting us know. I'm working on resolving this.

**Comment by avpeery** [comment]
Any update on this progress? just ran into the same issue

**Comment by bigtimebuddy** [comment]
@avpeery I started on this task, but was quickly blocked by TypeScript being out of date in the project. I needed to update one of our dependencies. I'll give this another shot and will try to get it in the next 7.3.3 release.

**Comment by avpeery** [comment]
Thanks @bigtimebuddy for addressing and fixing it quickly!! Do you know what release this fix will be in?
