### ISSUE TITLE
Angular Nightmare

### ISSUE THREAD

**Issue by colorao** [pixijs/pixijs#7026]
Angular + pixi is a complete nightmare to me:

**A: Started my project with  npm pixi 5.2.1 several months ago**
Worked fine

**B: Added npm pixi-particles 4.3.0**
Worked fine

**C: Updated to pixi 5.3.3**
Manual instantiation of Spritesheet crashed (cannot find baseTexture of null)
It worked fine in 5.2.1, but not in this version.
Also, some definitions are different (PIXI.interaction does not  exists) so I guess there are type and implementation differences (which I did not found  in the change list)
Smashed my head against the keyboard trying to instantiate Spritesheet manually ( without the loader) but no luck.

**D: Back to pixi 5.2.1**
Worked fine (interaction + Spritesheet)

**E: Install npm pixi-projection**
Not working at all
Definitions crashed. Mainly caused by
Type '(pos: IPointData, newPos: IPoint) => IPointData' is not assignable to type '(pos: IPointData, newPos: IPointData) => IPointData'.

**F: Uninstall npm pixi-projection**
But as I need it, I'll try to load it as an external file.
But in the repository, no individual .js file is to download. Just a module to npm install.
So, I pick the .js  in the npm module and load it as external (<script src="...">)  and trying to use it without definitions.

**G: external file implementation crashed when rendering:**
core.js:6185 ERROR TypeError: Cannot read property 'start' of undefined
    at BatchSystem.setObjectRenderer (core.es.js:5593)
    at Sprite3d._render (<anonymous>:3537:28)
    at Sprite3d.render (display.es.js:1728)
    at Camera3d.render (display.es.js:1733)
    at Container.render (display.es.js:1733)

**H: 2 years ago, I had similar problem with Angular + pixi (v4) + pixi-projection**
And finally solve it by joining pixi.min.js + pixi-projection.js in a single file and loading it at runtime (all together) 
This way I'll only needed pixi.js typescript definitions.

**I: Uninstall pixi.js + install @types/pixi.js** 
For me to have only the definitions inside Angular, but the implementation in the external .js file

**J: npm warns me that pixi.js has its own definitions, so definitions are not installed but pixi.js does.**
I'm not able to only use the definitions (as I did in the past) but instead,  forced to bundle pixi.js inside the project.
I cannot join pixi-projection.

By now  I'm unable to use pixi-projection.
npm module definitions are crashing, son my Angular TS project is not compiling.
And external .js loaded file has render problem.

PIXI is great and I use it for my work, but in Angular  TS is a real nightmare
I'm not sure what I'm doing wrong, but  I do need pixi-projection.
It works in the example pages, but  I'm not able to add it to my project.

I'd also like to update PIXI to the latest, but It crashes, in small details (but I need them)

I'd like if someone has a Angular + PIXI guide or any tip .....

Thanks in advanced

**Comment by uahic** [comment]
For my current project I installed 5.3.3 from scratch and it works fine (except for the fact pixi.js isnt recognizing my FF as 'webgl' enabled anymore -_- (other persons I let it try out had the same issue). I dont do this anymore: ```  import * as PIXI from 'pixi.js' ``` but rather ``` import { Graphics, Sprite , ... } from 'pixi.js' ```

**Comment by ivanpopelyshev** [comment]
@types/pixi.js are old v4 stuff.

most of the problems comes from two versions of pixi installed at the same time, just `rm -rf node_modules` , `rm package.lock` , `npm i`.

As `pixi-projection`, it requires PIXI to be in global scope. 

The best solution is to create another file, your own bundle, and re-export stuff:

```js
///<reference types='pixi-projection'/>
export * as PIXI from 'pixi.js';
window.PIXI = PIXI;
require('pixi-projection');
```

so, it reexports everything from pixi, you can import that file anywhere and its supposed to have everything. there might be a problem with typings - in that case try another approach - **provide** pixi globally in webpack config.

I'm honestly raging over all those issues for two years, and we still dont have full solution of how to make library with plugins that will work everywhere. We added countless workarounds for npm bugs, webpack bugs, typescript bugs and its always not enough.

**Comment by ivanpopelyshev** [comment]
> F: Uninstall npm pixi-projection
> But as I need it, I'll try to load it as an external file.
> But in the repository, no individual .js file is to download. Just a module to npm install.

You sure?

https://github.com/pixijs/pixi-projection/tree/master/dist
