### PR TITLE
Fix: Support building with TypeScript 5 with no errors

### LINKED ISSUE #9842: Bug: Tutorial code doesn't compile in TypeScript and PixiJS 7.3.2
### Current Behavior

I took the code example from the tutorial and I'm trying to compile it in TypeScript with the latest PIXI.JS and TypeScript versions. It throws errors:

```
[1] node_modules/@types/css-font-loading-module/index.d.ts(22,9): error TS2717: Subsequent property declarations must have the same type.  Property 'display' must be of type 'FontDisplay', but here has type 'string'.
[1] node_modules/@types/css-font-loading-module/index.d.ts(42,9): error TS2717: Subsequent property declarations must have the same type.  Property 'display' must be of type 'FontDisplay', but here has type 'string'.
```

https://github.com/martinsik/pixijs-7-typescript/blob/main/src/lib/index.ts

### Expected Behavior

It should compile without any errors.

### Steps to Reproduce

```
$ git clone https://github.com/martinsik/pixijs-7-typescript/
$ cd pixijs-7-typescript
$ npm ci
$ npm run serve
```

This will start concurrently a development server and TypeScript compiler in watch mode.

### Environment

- **`pixi.js` version**: *7.3.2*
- **OS & Version**: *OSX 13.6.1*
- **TypeScript version**: *5.2.2*

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Fixes #9842

### Fixes

* `@types/css-font-loading-module` was out-of-date
* Fix any eslint issues as a result of upgrading config

### Chores

* Requires upgrading to TypeScript v5
* Requires upgrading eslint toolchain and dependencies
* Move a bunch of default eslint rules to external config

### CODE REVIEW

File: packages/compressed-textures/src/const.ts [hunk 1]
```diff
@@ -116,9 +116,9 @@ export enum INTERNAL_FORMATS
      */
     COMPRESSED_RGB_ATC_WEBGL = 0x8C92,
     /**
-     * @default 0x8C92
+     * @default 0x8C93
      */
-    COMPRESSED_RGBA_ATC_EXPLICIT_ALPHA_WEBGL = 0x8C92, // TODO: Probably a bug on the MDN site
+    COMPRESSED_RGBA_ATC_EXPLICIT_ALPHA_WEBGL = 0x8C93,
```
Comment (bigtimebuddy) [inline packages/compressed-textures/src/const.ts:121]: Correct value in spec is here: https://registry.khronos.org/webgl/extensions/rejected/WEBGL_compressed_texture_atc/

MDN is likely wrong, e.g.: 
https://developer.mozilla.org/ja/docs/Web/API/WebGL_API/Constants#webgl_compressed_texture_atc

**Review by Zyie — APPROVED** [review]
