### ISSUE TITLE
generateCanvasTexture() function missing from PIXI.Graphics()

### ISSUE THREAD

**Issue by Chomiciak** [pixijs/pixijs#7331]
### Expected Behavior

```
var gt = new PIXI.Graphics();
gt.generateCanvasTexture();
````
Should generate a `PIXI.Texture` object.

### Current Behavior
Running the above code on `pixi.js-legacy:6.0.0` gives me the `generateCanvasTexture is not a function` error.

### Possible Solution
Ha! Don't know yet

### Steps to Reproduce
Install pixi.js-legacy version 6.0.0 with npm and run the code mentioned above.

### Environment

- **`pixi.js-legacy` version**: 6.0.0
- **Browser & Version**: Chrome 89, Firefox and Edge the newest versions 
- **OS & Version**: Npm 6.14.8 compiled on Ubuntu 20.04

**Comment by bigtimebuddy** [comment]
Unable to reproduce: https://jsfiddle.net/bigtimebuddy/3gnosqxy/ (Chrome 89)

**Comment by ivanpopelyshev** [comment]
the usual

```bash
rm -rf node_modules
rm package.lock
npm i
```

**Comment by Chomiciak** [comment]
I had the same error after updating to 6.0.0. Don't know if it is still present on newer versions. Back then it made me downgrade to 5.X.X.
