### ISSUE TITLE
Bug: Angular app, Cannot find modules ObservablePoint and PointData in node_modules/pixi.js/lib

### ISSUE THREAD

**Issue by monaxat** [pixijs/pixijs#11353]
### Current Behavior

Hi guys. 
I have a problem with pixi.js v8.9.0

I'm use Ionic + Angular + Pixi.js and packages installed from npm. Simple blank Ionic angular app only with three lines of code:
```
    const app = new Application();
    await app.init({width: 640, height: 360});

    this.renderer.appendChild(this.gameContainer?.nativeElement, app.canvas);
```

When I tried to run **ng serve** I got this errors:
```
X [ERROR] TS2307: Cannot find module '~/maths/point/PointData' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/pixi.js/lib/scene/sprite-nine-slice/NineSliceGeometry.d.ts:2:31:
      2 │ import { type PointData } from '~/maths/point/PointData';
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '~/maths/point/ObservablePoint' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/pixi.js/lib/scene/sprite-nine-slice/NineSliceSprite.d.ts:3:32:
      3 │ import { ObservablePoint } from '~/maths/point/ObservablePoint';
        ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '~/maths/point/PointData' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/pixi.js/lib/scene/sprite-nine-slice/NineSliceSprite.d.ts:4:31:
      4 │ import { type PointData } from '~/maths/point/PointData';
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~

```

Errors exists at v8.9.0 and v8.8.0. Version 8.7.3 works fine.

For quick fix, I'm directly edited .d.ts files import paths in the lib folder:
```
import { ObservablePoint } from '../../maths/point/ObservablePoint';
import { type PointData } from '../../maths/point/PointData';
```
And app runs fine for now, but this is not proper fix unfortunately. What I should to do? Rollback to 8.7.3 version or work with quick-fixed 8.9.0 or need to install pixi in some another way?

### Expected Behavior

**ng serve** command run app without errors 

### Steps to Reproduce

install ionic cli v7.0+
run **ionic new** and make blank Angular app. 
npm i pixi.js

replace code in the main.page.html to:
`<div style="flex: 1" #gameContainer></div>`

replace code in the main.page.ts to:
```
export class HomePage implements AfterViewInit {

  renderer = inject(Renderer2);

  @ViewChild('gameContainer', {
    read: ElementRef,
    static: true,
  }) gameContainer: ElementRef | undefined;

  async ngAfterViewInit() {
    const app = new Application();
    await app.init({width: 640, height: 360});

    this.renderer.appendChild(this.gameContainer?.nativeElement, app.canvas);
  }
}
```

then try to run **ng serve** or **ionic serve** 

### Environment

pixi.js: 8.9.0
Ionic cli: 7.2.1 
ionic/angular: 8.0.0
Angular: 19.0  
Standalone angular app

**Comment by Aron-bit202** [comment]
Hello i have a ploblem Whit '~/maths/point/PointData'; Is dot loding  help me.

**Comment by Aron-bit202** [comment]
I need to fix my code how to put in de creative code. Help!!! @weepy 

- [ 128674647272]  That is my code.

**Comment by Aron-bit202** [comment]
'~/maths/point/PointData'; 229
